import '../styles/globals.scss'
import { Inter } from 'next/font/google'
import NextAuthProvider from '@/components/provider'
import { CoinMarketCapProvider } from '@/context/context'
import Header from '../backbones/Header'
import Footer from '../backbones/Footer'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Cryptocurrency Prices, Charts and MarketCapilatizions',
  description: 'Generated by create next app',
}



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
          <CoinMarketCapProvider>
            <Header />
            {children}
            <Footer />
          </CoinMarketCapProvider>
        </NextAuthProvider>
      </body>
    </html>
  )
}
